import type { PaymentRailMetrics, Shipment } from "./types";

export const MOCK_SHIPMENTS: Shipment[] = [
  {
    id: "SHP-1001",
    reference: "MAEU-123456",
    status: "in_transit",
    origin: "Shanghai, CN",
    destination: "Los Angeles, US",
    corridor: "Shanghai → Los Angeles",
    carrier: "Maersk",
    customer: "Acme Electronics",
    freight: {
      mode: "ocean",
      incoterm: "FOB",
      vessel: "Maersk Horizon",
      container: "40' HC",
      lane: "Shanghai → Los Angeles",
      departure: "2025-11-05T04:00:00Z",
      eta: "2025-11-18T10:00:00Z",
      events: [
        {
          code: "LOAD",
          description: "Loaded at origin port",
          at: "2025-11-05T04:00:00Z",
          location: "Shanghai, CN",
        },
        {
          code: "DEPART",
          description: "Vessel departed",
          at: "2025-11-05T12:15:00Z",
          location: "Shanghai, CN",
        },
      ],
    },
    risk: {
      score: 82,
      category: "high",
      drivers: ["Port congestion", "Carrier capacity constraints"],
      assessed_at: "2025-11-11T08:30:00Z",
      watchlisted: true,
    },
    payment: {
      state: "partially_paid",
      total_valueUsd: 420000,
      released_usd: 252000,
      released_percentage: 60,
      holds_usd: 75000,
      milestones: [
        { milestone_id: "SHP-1001-0", label: "Pickup", percentage: 20, state: "released" },
        { milestone_id: "SHP-1001-1", label: "Mid-Voyage", percentage: 40, state: "released" },
        { milestone_id: "SHP-1001-2", label: "Berth", percentage: 20, state: "pending" },
        { milestone_id: "SHP-1001-3", label: "Delivery", percentage: 20, state: "blocked" },
      ],
      updatedAt: "2025-11-12T15:45:00Z",
    },
    governance: {
      proofpack_status: "VERIFIED",
      last_audit: "2025-11-12T09:00:00Z",
      exceptions: ["risk_spike", "payment_blocked"],
    },
  },
  {
    id: "SHP-1002",
    reference: "CMAU-998877",
    status: "delayed",
    origin: "Rotterdam, NL",
    destination: "New York, US",
    corridor: "Rotterdam → New York",
    carrier: "CMA CGM",
    customer: "Global Retail Co.",
    freight: {
      mode: "ocean",
      incoterm: "CIF",
      vessel: "CMA Liberty",
      container: "40' STD",
      lane: "Rotterdam → New York",
      departure: "2025-11-04T06:00:00Z",
      eta: "2025-11-16T18:00:00Z",
      events: [
        {
          code: "HOLD",
          description: "Held at transshipment terminal",
          at: "2025-11-09T11:20:00Z",
          location: "Algeciras, ES",
        },
      ],
    },
    risk: {
      score: 67,
      category: "medium",
      drivers: ["Weather diversion"],
      assessed_at: "2025-11-12T06:15:00Z",
    },
    payment: {
      state: "in_progress",
      total_valueUsd: 310000,
      released_usd: 139500,
      released_percentage: 45,
      holds_usd: 0,
      milestones: [
        { milestone_id: "SHP-1002-0", label: "Pickup", percentage: 25, state: "released" },
        { milestone_id: "SHP-1002-1", label: "Customs", percentage: 25, state: "pending" },
        { milestone_id: "SHP-1002-2", label: "Delivery", percentage: 50, state: "pending" },
      ],
      updatedAt: "2025-11-12T10:40:00Z",
    },
    governance: {
      proofpack_status: "PENDING",
      last_audit: "2025-11-11T19:00:00Z",
      exceptions: ["late_delivery"],
    },
  },
  {
    id: "SHP-1003",
    reference: "ONEU-445566",
    status: "completed",
    origin: "Hamburg, DE",
    destination: "Houston, US",
    corridor: "Hamburg → Houston",
    carrier: "ONE",
    customer: "AutoParts USA",
    freight: {
      mode: "ocean",
      incoterm: "DAP",
      vessel: "ONE Odyssey",
      container: "20' STD",
      lane: "Hamburg → Houston",
      departure: "2025-10-28T05:30:00Z",
      eta: "2025-11-10T12:00:00Z",
      events: [
        {
          code: "DELIVERY",
          description: "Delivered to consignee",
          at: "2025-11-10T11:30:00Z",
          location: "Houston, US",
        },
      ],
    },
    risk: {
      score: 18,
      category: "low",
      drivers: ["Strong carrier performance"],
      assessed_at: "2025-11-10T13:05:00Z",
    },
    payment: {
      state: "completed",
      total_valueUsd: 185000,
      released_usd: 185000,
      released_percentage: 100,
      holds_usd: 0,
      milestones: [
        { milestone_id: "SHP-1003-0", label: "Pickup", percentage: 30, state: "released" },
        { milestone_id: "SHP-1003-1", label: "Sailing", percentage: 40, state: "released" },
        { milestone_id: "SHP-1003-2", label: "Delivery", percentage: 30, state: "released" },
      ],
      updatedAt: "2025-11-11T08:00:00Z",
    },
    governance: {
      proofpack_status: "VERIFIED",
      last_audit: "2025-11-11T08:00:00Z",
      exceptions: [],
    },
  },
  {
    id: "SHP-1004",
    reference: "HLCU-777888",
    status: "blocked",
    origin: "Singapore, SG",
    destination: "Long Beach, US",
    corridor: "Singapore → Long Beach",
    carrier: "Hapag-Lloyd",
    customer: "MegaMart",
    freight: {
      mode: "ocean",
      incoterm: "FOB",
      vessel: "Hapag Aurora",
      container: "45' HC",
      lane: "Singapore → Long Beach",
      departure: "2025-11-07T09:20:00Z",
      eta: "2025-11-20T09:30:00Z",
      events: [
        {
          code: "INSPECT",
          description: "US Customs inspection",
          at: "2025-11-12T16:00:00Z",
          location: "Long Beach, US",
        },
      ],
    },
    risk: {
      score: 91,
      category: "high",
      drivers: ["Customs hold", "Outstanding documentation"],
      assessed_at: "2025-11-12T20:10:00Z",
      watchlisted: true,
    },
    payment: {
      state: "blocked",
      total_valueUsd: 560000,
      released_usd: 112000,
      released_percentage: 20,
      holds_usd: 320000,
      milestones: [
        { milestone_id: "SHP-1004-0", label: "Pickup", percentage: 20, state: "released" },
        { milestone_id: "SHP-1004-1", label: "Port", percentage: 30, state: "blocked" },
        { milestone_id: "SHP-1004-2", label: "Delivery", percentage: 50, state: "blocked" },
      ],
      updatedAt: "2025-11-12T21:00:00Z",
    },
    governance: {
      proofpack_status: "FAILED",
      last_audit: "2025-11-12T22:45:00Z",
      exceptions: ["payment_blocked", "risk_spike", "late_delivery"],
    },
  },
  {
    id: "SHP-1005",
    reference: "FXTU-222333",
    status: "pickup",
    origin: "Ho Chi Minh City, VN",
    destination: "Seattle, US",
    corridor: "Ho Chi Minh City → Seattle",
    carrier: "Flexport",
    customer: "NeoHome",
    freight: {
      mode: "air",
      incoterm: "EXW",
      vessel: "FXT Flight 982",
      container: "ULD",
      lane: "HCMC → Seattle",
      departure: null,
      eta: "2025-11-15T21:00:00Z",
      events: [],
    },
    risk: {
      score: 34,
      category: "medium",
      drivers: ["First-time supplier"],
      assessed_at: "2025-11-12T05:00:00Z",
    },
    payment: {
      state: "not_started",
      total_valueUsd: 98000,
      released_usd: 0,
      released_percentage: 0,
      holds_usd: 0,
      milestones: [
        { milestone_id: "SHP-1005-0", label: "Pickup", percentage: 30, state: "pending" },
        { milestone_id: "SHP-1005-1", label: "Departure", percentage: 30, state: "pending" },
        { milestone_id: "SHP-1005-2", label: "Delivery", percentage: 40, state: "pending" },
      ],
      updatedAt: "2025-11-11T17:15:00Z",
    },
    governance: {
      proofpack_status: "PENDING",
      last_audit: "2025-11-11T17:15:00Z",
      exceptions: ["no_update"],
    },
  },
  // Additional realistic demo shipments
  {
    id: "SHP-2001",
    reference: "COSCO-789012",
    status: "delayed",
    origin: "Ningbo, CN",
    destination: "Rotterdam, NL",
    corridor: "Ningbo → Rotterdam",
    carrier: "COSCO Shipping",
    customer: "Eurotech Manufacturing",
    freight: {
      mode: "ocean",
      incoterm: "CIF",
      vessel: "COSCO Universe",
      container: "40' HC",
      lane: "Ningbo → Rotterdam",
      departure: "2025-10-20T08:00:00Z",
      eta: "2025-11-25T16:00:00Z",
      events: [
        {
          code: "LOAD",
          description: "Container loaded",
          at: "2025-10-20T08:00:00Z",
          location: "Ningbo, CN",
        },
        {
          code: "DELAY",
          description: "Port congestion delay",
          at: "2025-11-15T12:00:00Z",
          location: "Suez Canal",
        },
      ],
    },
    risk: {
      score: 91,
      category: "high",
      drivers: ["Port congestion", "Weather delays", "Canal blockage"],
      assessed_at: "2025-11-15T14:30:00Z",
      watchlisted: true,
    },
    payment: {
      state: "blocked",
      total_valueUsd: 850000,
      released_usd: 170000,
      released_percentage: 20,
      holds_usd: 680000,
      milestones: [
        { milestone_id: "SHP-2001-0", label: "Pickup", percentage: 20, state: "released" },
        { milestone_id: "SHP-2001-1", label: "Port Loading", percentage: 25, state: "blocked" },
        { milestone_id: "SHP-2001-2", label: "Transit", percentage: 30, state: "pending" },
        { milestone_id: "SHP-2001-3", label: "Delivery", percentage: 25, state: "pending" },
      ],
      updatedAt: "2025-11-15T14:30:00Z",
    },
    governance: {
      proofpack_status: "FAILED",
      last_audit: "2025-11-15T12:00:00Z",
      exceptions: ["late_delivery", "payment_blocked"],
    },
  },
  {
    id: "SHP-2002",
    reference: "HAPAG-334455",
    status: "in_transit",
    origin: "Santos, BR",
    destination: "Miami, US",
    corridor: "Santos → Miami",
    carrier: "Hapag-Lloyd",
    customer: "Tropical Foods Inc",
    freight: {
      mode: "ocean",
      incoterm: "FOB",
      vessel: "Buenos Aires Express",
      container: "40' RF",
      lane: "Santos → Miami",
      departure: "2025-11-12T14:30:00Z",
      eta: "2025-11-22T09:00:00Z",
      events: [
        {
          code: "LOAD",
          description: "Reefer container loaded",
          at: "2025-11-12T14:30:00Z",
          location: "Santos, BR",
        },
        {
          code: "TEMP_CHECK",
          description: "Temperature maintained at -18°C",
          at: "2025-11-16T06:00:00Z",
          location: "Atlantic Ocean",
        },
      ],
    },
    risk: {
      score: 35,
      category: "medium",
      drivers: ["Reefer dependency", "Seasonal demand"],
      assessed_at: "2025-11-16T08:15:00Z",
    },
    payment: {
      state: "in_progress",
      total_valueUsd: 320000,
      released_usd: 96000,
      released_percentage: 30,
      holds_usd: 0,
      milestones: [
        { milestone_id: "SHP-2002-0", label: "Pickup", percentage: 30, state: "released" },
        { milestone_id: "SHP-2002-1", label: "Export Docs", percentage: 25, state: "pending" },
        { milestone_id: "SHP-2002-2", label: "Arrival", percentage: 25, state: "pending" },
        { milestone_id: "SHP-2002-3", label: "Delivery", percentage: 20, state: "pending" },
      ],
      updatedAt: "2025-11-16T08:15:00Z",
    },
    governance: {
      proofpack_status: "VERIFIED",
      last_audit: "2025-11-16T08:15:00Z",
      exceptions: [],
    },
  },
  {
    id: "SHP-2003",
    reference: "EVERGREEN-667788",
    status: "completed",
    origin: "Kaohsiung, TW",
    destination: "Long Beach, US",
    corridor: "Kaohsiung → Long Beach",
    carrier: "Evergreen",
    customer: "Pacific Tech Solutions",
    freight: {
      mode: "ocean",
      incoterm: "DAP",
      vessel: "Ever Given",
      container: "20' STD",
      lane: "Kaohsiung → Long Beach",
      departure: "2025-10-25T11:45:00Z",
      eta: "2025-11-08T14:00:00Z",
      events: [
        {
          code: "DELIVERY",
          description: "Container delivered successfully",
          at: "2025-11-08T13:30:00Z",
          location: "Long Beach, US",
        },
      ],
    },
    risk: {
      score: 15,
      category: "low",
      drivers: ["Reliable carrier", "Established route"],
      assessed_at: "2025-11-08T15:00:00Z",
    },
    payment: {
      state: "completed",
      total_valueUsd: 275000,
      released_usd: 275000,
      released_percentage: 100,
      holds_usd: 0,
      milestones: [
        { milestone_id: "SHP-2003-0", label: "Pickup", percentage: 25, state: "released" },
        { milestone_id: "SHP-2003-1", label: "Loading", percentage: 25, state: "released" },
        { milestone_id: "SHP-2003-2", label: "Transit", percentage: 25, state: "released" },
        { milestone_id: "SHP-2003-3", label: "Delivery", percentage: 25, state: "released" },
      ],
      updatedAt: "2025-11-08T15:00:00Z",
    },
    governance: {
      proofpack_status: "VERIFIED",
      last_audit: "2025-11-08T15:00:00Z",
      exceptions: [],
    },
  },
  {
    id: "SHP-2004",
    reference: "MSC-445577",
    status: "delayed",
    origin: "Felixstowe, UK",
    destination: "New York, US",
    corridor: "Felixstowe → New York",
    carrier: "MSC",
    customer: "Atlantic Imports Ltd",
    freight: {
      mode: "ocean",
      incoterm: "EXW",
      vessel: "MSC Meraviglia",
      container: "40' HC",
      lane: "Felixstowe → New York",
      departure: "2025-11-01T19:20:00Z",
      eta: "2025-11-15T08:00:00Z",
      events: [
        {
          code: "CUSTOMS_HOLD",
          description: "Customs inspection required",
          at: "2025-11-14T10:15:00Z",
          location: "New York, US",
        },
      ],
    },
    risk: {
      score: 78,
      category: "high",
      drivers: ["Customs hold", "Documentation issues"],
      assessed_at: "2025-11-14T11:00:00Z",
      watchlisted: true,
    },
    payment: {
      state: "blocked",
      total_valueUsd: 590000,
      released_usd: 177000,
      released_percentage: 30,
      holds_usd: 413000,
      milestones: [
        { milestone_id: "SHP-2004-0", label: "Pickup", percentage: 30, state: "released" },
        { milestone_id: "SHP-2004-1", label: "Customs", percentage: 35, state: "blocked" },
        { milestone_id: "SHP-2004-2", label: "Delivery", percentage: 35, state: "pending" },
      ],
      updatedAt: "2025-11-14T11:00:00Z",
    },
    governance: {
      proofpack_status: "FAILED",
      last_audit: "2025-11-14T11:00:00Z",
      exceptions: ["no_update", "payment_blocked"],
    },
  },
  {
    id: "SHP-2005",
    reference: "CMA-998877",
    status: "in_transit",
    origin: "Le Havre, FR",
    destination: "Montreal, CA",
    corridor: "Le Havre → Montreal",
    carrier: "CMA CGM",
    customer: "Northern Logistics",
    freight: {
      mode: "ocean",
      incoterm: "CFR",
      vessel: "CMA CGM Kerguelen",
      container: "20' STD",
      lane: "Le Havre → Montreal",
      departure: "2025-11-10T07:00:00Z",
      eta: "2025-11-20T15:30:00Z",
      events: [
        {
          code: "TRANSIT",
          description: "Vessel in North Atlantic",
          at: "2025-11-16T12:00:00Z",
          location: "North Atlantic",
        },
      ],
    },
    risk: {
      score: 42,
      category: "medium",
      drivers: ["Weather conditions", "Winter season"],
      assessed_at: "2025-11-16T14:20:00Z",
    },
    payment: {
      state: "in_progress",
      total_valueUsd: 195000,
      released_usd: 58500,
      released_percentage: 30,
      holds_usd: 0,
      milestones: [
        { milestone_id: "SHP-2005-0", label: "Pickup", percentage: 30, state: "released" },
        { milestone_id: "SHP-2005-1", label: "Loading", percentage: 25, state: "pending" },
        { milestone_id: "SHP-2005-2", label: "Arrival", percentage: 25, state: "pending" },
        { milestone_id: "SHP-2005-3", label: "Delivery", percentage: 20, state: "pending" },
      ],
      updatedAt: "2025-11-16T14:20:00Z",
    },
    governance: {
      proofpack_status: "VERIFIED",
      last_audit: "2025-11-16T14:20:00Z",
      exceptions: [],
    },
  },
  {
    id: "SHP-2006",
    reference: "YANG-112233",
    status: "delayed",
    origin: "Busan, KR",
    destination: "Vancouver, CA",
    corridor: "Busan → Vancouver",
    carrier: "Yang Ming",
    customer: "Pacific Rim Trading",
    freight: {
      mode: "ocean",
      incoterm: "DAP",
      vessel: "YM Excellence",
      container: "40' HC",
      lane: "Busan → Vancouver",
      departure: "2025-10-28T16:45:00Z",
      eta: "2025-11-18T10:00:00Z",
      events: [
        {
          code: "WEATHER_DELAY",
          description: "Storm delay in Pacific",
          at: "2025-11-12T18:30:00Z",
          location: "North Pacific",
        },
      ],
    },
    risk: {
      score: 68,
      category: "high",
      drivers: ["Weather delays", "Pacific storm season"],
      assessed_at: "2025-11-12T20:00:00Z",
      watchlisted: true,
    },
    payment: {
      state: "partially_paid",
      total_valueUsd: 445000,
      released_usd: 133500,
      released_percentage: 30,
      holds_usd: 89000,
      milestones: [
        { milestone_id: "SHP-2006-0", label: "Pickup", percentage: 30, state: "released" },
        { milestone_id: "SHP-2006-1", label: "Transit", percentage: 35, state: "blocked" },
        { milestone_id: "SHP-2006-2", label: "Delivery", percentage: 35, state: "pending" },
      ],
      updatedAt: "2025-11-12T20:00:00Z",
    },
    governance: {
      proofpack_status: "PENDING",
      last_audit: "2025-11-12T20:00:00Z",
      exceptions: ["late_delivery", "risk_spike"],
    },
  },
  {
    id: "SHP-2007",
    reference: "OOCL-556699",
    status: "completed",
    origin: "Hong Kong, HK",
    destination: "Oakland, US",
    corridor: "Hong Kong → Oakland",
    carrier: "OOCL",
    customer: "Bay Area Electronics",
    freight: {
      mode: "ocean",
      incoterm: "FOB",
      vessel: "OOCL Innovation",
      container: "20' STD",
      lane: "Hong Kong → Oakland",
      departure: "2025-10-18T09:15:00Z",
      eta: "2025-11-01T13:00:00Z",
      events: [
        {
          code: "DELIVERY",
          description: "Early delivery completed",
          at: "2025-10-31T11:45:00Z",
          location: "Oakland, US",
        },
      ],
    },
    risk: {
      score: 12,
      category: "low",
      drivers: ["Premium service", "Dedicated capacity"],
      assessed_at: "2025-10-31T12:30:00Z",
    },
    payment: {
      state: "completed",
      total_valueUsd: 380000,
      released_usd: 380000,
      released_percentage: 100,
      holds_usd: 0,
      milestones: [
        { milestone_id: "SHP-2007-0", label: "Pickup", percentage: 25, state: "released" },
        { milestone_id: "SHP-2007-1", label: "Export", percentage: 25, state: "released" },
        { milestone_id: "SHP-2007-2", label: "Import", percentage: 25, state: "released" },
        { milestone_id: "SHP-2007-3", label: "Delivery", percentage: 25, state: "released" },
      ],
      updatedAt: "2025-10-31T12:30:00Z",
    },
    governance: {
      proofpack_status: "VERIFIED",
      last_audit: "2025-10-31T12:30:00Z",
      exceptions: [],
    },
  },
  {
    id: "SHP-2008",
    reference: "ZIM-778899",
    status: "in_transit",
    origin: "Haifa, IL",
    destination: "Savannah, US",
    corridor: "Haifa → Savannah",
    carrier: "ZIM",
    customer: "Mediterranean Trading Co",
    freight: {
      mode: "ocean",
      incoterm: "CIF",
      vessel: "ZIM Vancouver",
      container: "40' STD",
      lane: "Haifa → Savannah",
      departure: "2025-11-08T20:30:00Z",
      eta: "2025-11-25T12:00:00Z",
      events: [
        {
          code: "SUEZ_TRANSIT",
          description: "Transiting Suez Canal",
          at: "2025-11-09T14:00:00Z",
          location: "Suez Canal, EG",
        },
      ],
    },
    risk: {
      score: 55,
      category: "medium",
      drivers: ["Canal dependency", "Regional tensions"],
      assessed_at: "2025-11-09T16:00:00Z",
    },
    payment: {
      state: "in_progress",
      total_valueUsd: 225000,
      released_usd: 45000,
      released_percentage: 20,
      holds_usd: 0,
      milestones: [
        { milestone_id: "SHP-2008-0", label: "Pickup", percentage: 20, state: "released" },
        { milestone_id: "SHP-2008-1", label: "Export Clearance", percentage: 30, state: "pending" },
        { milestone_id: "SHP-2008-2", label: "Ocean Transit", percentage: 30, state: "pending" },
        { milestone_id: "SHP-2008-3", label: "Delivery", percentage: 20, state: "pending" },
      ],
      updatedAt: "2025-11-09T16:00:00Z",
    },
    governance: {
      proofpack_status: "VERIFIED",
      last_audit: "2025-11-09T16:00:00Z",
      exceptions: [],
    },
  },
];

export const MOCK_PAYMENT_RAILS_METRICS: PaymentRailMetrics[] = [
  {
    id: "bank_wire",
    label: "Cross-Border Bank Wire",
    description: "Legacy correspondent payouts via bilateral bank rails",
    avg_settlement_hours: 36,
    avg_fee_usd: 25,
    avg_fx_spread_bps: 18,
    fail_rate_bps: 45,
    capital_locked_hours: 48,
  },
  {
    id: "ach",
    label: "ACH",
    description: "Domestic batch clearing (ACH / SEPA)",
    avg_settlement_hours: 24,
    avg_fee_usd: 1.25,
    avg_fx_spread_bps: 12,
    fail_rate_bps: 35,
    capital_locked_hours: 24,
  },
  {
    id: "swift",
    label: "SWIFT MT103",
    description: "Cross-border correspondent banking via MT103",
    avg_settlement_hours: 48,
    avg_fee_usd: 35,
    avg_fx_spread_bps: 22,
    fail_rate_bps: 60,
    capital_locked_hours: 60,
  },
  {
    id: "blockchain",
    label: "Permissioned Blockchain Rail",
    description: "ChainBridge settlement cluster (permissioned L2)",
    avg_settlement_hours: 1.5,
    avg_fee_usd: 0.35,
    avg_fx_spread_bps: 2,
    fail_rate_bps: 5,
    capital_locked_hours: 1,
  },
  {
    id: "blockchain",
    label: "Central Bank Digital Currency",
    description: "Direct CBDC settlements via central bank infrastructure",
    avg_settlement_hours: 0.5,
    avg_fee_usd: 0.15,
    avg_fx_spread_bps: 1,
    fail_rate_bps: 2,
    capital_locked_hours: 0.5,
  },
  {
    id: "swift",
    label: "Correspondent Banking",
    description: "Traditional nostro/vostro account settlements",
    avg_settlement_hours: 72,
    avg_fee_usd: 45,
    avg_fx_spread_bps: 28,
    fail_rate_bps: 85,
    capital_locked_hours: 96,
  },
  {
    id: "bank_wire",
    label: "Letters of Credit",
    description: "Documentary credit via banking consortium",
    avg_settlement_hours: 168,
    avg_fee_usd: 250,
    avg_fx_spread_bps: 35,
    fail_rate_bps: 120,
    capital_locked_hours: 240,
  },
];

// Additional demo data for enhanced Control Tower experience
export const DEMO_MARKET_CONDITIONS = {
  global_capacity_utilization: 0.87,
  avg_port_congestion_days: 4.2,
  fuel_price_trend: "increasing",
  seasonal_demand_factor: 1.15,
  geopolitical_riskScore: 62,
  weather_disruption_probability: 0.23,
};

export const DEMO_CARRIER_PERFORMANCE = [
  { carrier: "Maersk", on_time_performance: 0.94, capacity_score: 0.91, cost_index: 1.05 },
  { carrier: "MSC", on_time_performance: 0.89, capacity_score: 0.88, cost_index: 0.98 },
  { carrier: "COSCO", on_time_performance: 0.85, capacity_score: 0.93, cost_index: 0.92 },
  { carrier: "CMA CGM", on_time_performance: 0.87, capacity_score: 0.86, cost_index: 1.02 },
  { carrier: "Hapag-Lloyd", on_time_performance: 0.91, capacity_score: 0.84, cost_index: 1.08 },
  { carrier: "Evergreen", on_time_performance: 0.88, capacity_score: 0.89, cost_index: 0.95 },
  { carrier: "OOCL", on_time_performance: 0.93, capacity_score: 0.82, cost_index: 1.12 },
  { carrier: "Yang Ming", on_time_performance: 0.83, capacity_score: 0.79, cost_index: 0.89 },
];

export const DEMO_TRADE_LANES = [
  {
    route: "Asia → North America",
    volume_teu: 12450000,
    avg_transit_days: 14,
    congestion_factor: 1.23,
    rate_trend: "stable"
  },
  {
    route: "Asia → Europe",
    volume_teu: 9850000,
    avg_transit_days: 21,
    congestion_factor: 1.45,
    rate_trend: "increasing"
  },
  {
    route: "Europe → North America",
    volume_teu: 3200000,
    avg_transit_days: 8,
    congestion_factor: 0.95,
    rate_trend: "decreasing"
  },
  {
    route: "Intra-Asia",
    volume_teu: 8900000,
    avg_transit_days: 5,
    congestion_factor: 1.15,
    rate_trend: "stable"
  },
];

// Real-world port performance data for demo
export const DEMO_PORT_PERFORMANCE = [
  { port: "Shanghai", country: "CN", congestion_days: 2.1, efficiency_score: 0.94, volume_rank: 1 },
  { port: "Singapore", country: "SG", congestion_days: 0.8, efficiency_score: 0.97, volume_rank: 2 },
  { port: "Rotterdam", country: "NL", congestion_days: 1.2, efficiency_score: 0.93, volume_rank: 10 },
  { port: "Los Angeles", country: "US", congestion_days: 5.3, efficiency_score: 0.78, volume_rank: 9 },
  { port: "Long Beach", country: "US", congestion_days: 4.7, efficiency_score: 0.81, volume_rank: 11 },
  { port: "Hamburg", country: "DE", congestion_days: 1.8, efficiency_score: 0.89, volume_rank: 13 },
  { port: "Antwerp", country: "BE", congestion_days: 1.5, efficiency_score: 0.91, volume_rank: 14 },
  { port: "Felixstowe", country: "UK", congestion_days: 3.2, efficiency_score: 0.85, volume_rank: 29 },
];

// Historical rate data for demo analytics
export const DEMO_HISTORICAL_RATES = {
  "Shanghai → Los Angeles": [
    { date: "2025-10-01", rate_per_teu: 2850, utilization: 0.89 },
    { date: "2025-10-15", rate_per_teu: 3120, utilization: 0.92 },
    { date: "2025-11-01", rate_per_teu: 3350, utilization: 0.87 },
    { date: "2025-11-15", rate_per_teu: 3180, utilization: 0.91 },
  ],
  "Ningbo → Rotterdam": [
    { date: "2025-10-01", rate_per_teu: 4200, utilization: 0.85 },
    { date: "2025-10-15", rate_per_teu: 4850, utilization: 0.93 },
    { date: "2025-11-01", rate_per_teu: 5100, utilization: 0.88 },
    { date: "2025-11-15", rate_per_teu: 4950, utilization: 0.90 },
  ],
};

// Supply chain disruption events for enhanced realism
export const DEMO_DISRUPTION_EVENTS = [
  {
    id: "DISRUPT-001",
    type: "Weather",
    description: "Pacific storm system affecting trans-Pacific routes",
    affected_routes: ["Asia → North America"],
    severity: "Medium",
    duration_hours: 72,
    impact_score: 0.65,
    active: true,
  },
  {
    id: "DISRUPT-002",
    type: "Port Congestion",
    description: "Labor dispute at Los Angeles/Long Beach port complex",
    affected_routes: ["Asia → North America"],
    severity: "High",
    duration_hours: 168,
    impact_score: 0.85,
    active: false,
  },
  {
    id: "DISRUPT-003",
    type: "Canal",
    description: "Reduced capacity through Suez Canal due to maintenance",
    affected_routes: ["Asia → Europe"],
    severity: "Medium",
    duration_hours: 96,
    impact_score: 0.45,
    active: true,
  },
];
