import type { PaymentRailMetrics, Shipment } from "./types";

export const MOCK_SHIPMENTS: Shipment[] = [
  {
    id: "SHP-1001",
    reference: "MAEU-123456",
    status: "in_transit",
    origin: "Shanghai, CN",
    destination: "Los Angeles, US",
    carrier: "Maersk",
    customer: "Acme Electronics",
    freight: {
      mode: "ocean",
      incoterm: "FOB",
      vessel: "Maersk Horizon",
      container: "40' HC",
      lane: "Shanghai → Los Angeles",
      departure: "2025-11-05T04:00:00Z",
      eta: "2025-11-18T10:00:00Z",
      events: [
        {
          code: "LOAD",
          description: "Loaded at origin port",
          at: "2025-11-05T04:00:00Z",
          location: "Shanghai, CN",
        },
        {
          code: "DEPART",
          description: "Vessel departed",
          at: "2025-11-05T12:15:00Z",
          location: "Shanghai, CN",
        },
      ],
    },
    risk: {
      score: 82,
      category: "high",
      drivers: ["Port congestion", "Carrier capacity constraints"],
      assessedAt: "2025-11-11T08:30:00Z",
      watchlisted: true,
    },
    payment: {
      state: "partially_paid",
      totalValueUsd: 420000,
      releasedPercentage: 60,
      holdsUsd: 75000,
      milestones: [
        { label: "Pickup", percentage: 20, state: "released" },
        { label: "Mid-Voyage", percentage: 40, state: "released" },
        { label: "Berth", percentage: 20, state: "pending" },
        { label: "Delivery", percentage: 20, state: "blocked" },
      ],
      updatedAt: "2025-11-12T15:45:00Z",
    },
    governance: {
      proofpackStatus: "VERIFIED",
      lastAudit: "2025-11-12T09:00:00Z",
      exceptions: ["risk_spike", "payment_blocked"],
    },
  },
  {
    id: "SHP-1002",
    reference: "CMAU-998877",
    status: "delayed",
    origin: "Rotterdam, NL",
    destination: "New York, US",
    carrier: "CMA CGM",
    customer: "Global Retail Co.",
    freight: {
      mode: "ocean",
      incoterm: "CIF",
      vessel: "CMA Liberty",
      container: "40' STD",
      lane: "Rotterdam → New York",
      departure: "2025-11-04T06:00:00Z",
      eta: "2025-11-16T18:00:00Z",
      events: [
        {
          code: "HOLD",
          description: "Held at transshipment terminal",
          at: "2025-11-09T11:20:00Z",
          location: "Algeciras, ES",
        },
      ],
    },
    risk: {
      score: 67,
      category: "medium",
      drivers: ["Weather diversion"],
      assessedAt: "2025-11-12T06:15:00Z",
    },
    payment: {
      state: "in_progress",
      totalValueUsd: 310000,
      releasedPercentage: 45,
      holdsUsd: 0,
      milestones: [
        { label: "Pickup", percentage: 25, state: "released" },
        { label: "Customs", percentage: 25, state: "pending" },
        { label: "Delivery", percentage: 50, state: "pending" },
      ],
      updatedAt: "2025-11-12T10:40:00Z",
    },
    governance: {
      proofpackStatus: "PENDING",
      lastAudit: "2025-11-11T19:00:00Z",
      exceptions: ["late_delivery"],
    },
  },
  {
    id: "SHP-1003",
    reference: "ONEU-445566",
    status: "completed",
    origin: "Hamburg, DE",
    destination: "Houston, US",
    carrier: "ONE",
    customer: "AutoParts USA",
    freight: {
      mode: "ocean",
      incoterm: "DAP",
      vessel: "ONE Odyssey",
      container: "20' STD",
      lane: "Hamburg → Houston",
      departure: "2025-10-28T05:30:00Z",
      eta: "2025-11-10T12:00:00Z",
      events: [
        {
          code: "DELIVERY",
          description: "Delivered to consignee",
          at: "2025-11-10T11:30:00Z",
          location: "Houston, US",
        },
      ],
    },
    risk: {
      score: 18,
      category: "low",
      drivers: ["Strong carrier performance"],
      assessedAt: "2025-11-10T13:05:00Z",
    },
    payment: {
      state: "completed",
      totalValueUsd: 185000,
      releasedPercentage: 100,
      holdsUsd: 0,
      milestones: [
        { label: "Pickup", percentage: 30, state: "released" },
        { label: "Sailing", percentage: 40, state: "released" },
        { label: "Delivery", percentage: 30, state: "released" },
      ],
      updatedAt: "2025-11-11T08:00:00Z",
    },
    governance: {
      proofpackStatus: "VERIFIED",
      lastAudit: "2025-11-11T08:00:00Z",
      exceptions: [],
    },
  },
  {
    id: "SHP-1004",
    reference: "HLCU-777888",
    status: "blocked",
    origin: "Singapore, SG",
    destination: "Long Beach, US",
    carrier: "Hapag-Lloyd",
    customer: "MegaMart",
    freight: {
      mode: "ocean",
      incoterm: "FOB",
      vessel: "Hapag Aurora",
      container: "45' HC",
      lane: "Singapore → Long Beach",
      departure: "2025-11-07T09:20:00Z",
      eta: "2025-11-20T09:30:00Z",
      events: [
        {
          code: "INSPECT",
          description: "US Customs inspection",
          at: "2025-11-12T16:00:00Z",
          location: "Long Beach, US",
        },
      ],
    },
    risk: {
      score: 91,
      category: "high",
      drivers: ["Customs hold", "Outstanding documentation"],
      assessedAt: "2025-11-12T20:10:00Z",
      watchlisted: true,
    },
    payment: {
      state: "blocked",
      totalValueUsd: 560000,
      releasedPercentage: 20,
      holdsUsd: 320000,
      milestones: [
        { label: "Pickup", percentage: 20, state: "released" },
        { label: "Port", percentage: 30, state: "blocked" },
        { label: "Delivery", percentage: 50, state: "blocked" },
      ],
      updatedAt: "2025-11-12T21:00:00Z",
    },
    governance: {
      proofpackStatus: "FAILED",
      lastAudit: "2025-11-12T22:45:00Z",
      exceptions: ["payment_blocked", "risk_spike", "late_delivery"],
    },
  },
  {
    id: "SHP-1005",
    reference: "FXTU-222333",
    status: "pickup",
    origin: "Ho Chi Minh City, VN",
    destination: "Seattle, US",
    carrier: "Flexport",
    customer: "NeoHome",
    freight: {
      mode: "air",
      incoterm: "EXW",
      vessel: "FXT Flight 982",
      container: "ULD",
      lane: "HCMC → Seattle",
      departure: null,
      eta: "2025-11-15T21:00:00Z",
      events: [],
    },
    risk: {
      score: 34,
      category: "medium",
      drivers: ["First-time supplier"],
      assessedAt: "2025-11-12T05:00:00Z",
    },
    payment: {
      state: "not_started",
      totalValueUsd: 98000,
      releasedPercentage: 0,
      holdsUsd: 0,
      milestones: [
        { label: "Pickup", percentage: 30, state: "pending" },
        { label: "Departure", percentage: 30, state: "pending" },
        { label: "Delivery", percentage: 40, state: "pending" },
      ],
      updatedAt: "2025-11-11T17:15:00Z",
    },
    governance: {
      proofpackStatus: "PENDING",
      lastAudit: "2025-11-11T17:15:00Z",
      exceptions: ["no_update"],
    },
  },
];

export const MOCK_PAYMENT_RAILS_METRICS: PaymentRailMetrics[] = [
  {
    id: "bank_wire",
    label: "Cross-Border Bank Wire",
    description: "Legacy correspondent payouts via bilateral bank rails",
    avg_settlement_hours: 36,
    avg_fee_usd: 25,
    avg_fx_spread_bps: 18,
    fail_rate_bps: 45,
    capital_locked_hours: 48,
  },
  {
    id: "ach",
    label: "ACH",
    description: "Domestic batch clearing (ACH / SEPA)",
    avg_settlement_hours: 24,
    avg_fee_usd: 1.25,
    avg_fx_spread_bps: 12,
    fail_rate_bps: 35,
    capital_locked_hours: 24,
  },
  {
    id: "swift",
    label: "SWIFT MT103",
    description: "Cross-border correspondent banking via MT103",
    avg_settlement_hours: 48,
    avg_fee_usd: 35,
    avg_fx_spread_bps: 22,
    fail_rate_bps: 60,
    capital_locked_hours: 60,
  },
  {
    id: "blockchain",
    label: "Permissioned Blockchain Rail",
    description: "ChainBridge settlement cluster (permissioned L2)",
    avg_settlement_hours: 1.5,
    avg_fee_usd: 0.35,
    avg_fx_spread_bps: 2,
    fail_rate_bps: 5,
    capital_locked_hours: 1,
  },
];
