"""
Core Governance Module — ALEX Runtime Enforcement

This module implements hard runtime enforcement of the Agent Capability Manifest (ACM).
ALEX (GID-08) is the sole authority for evaluating and denying agent intents.

Enforcement principles:
- Default Deny: Absence of permission = rejection
- No Prompt Reliance: Enforcement is code-only
- No Silent Failure: Every denial emits a structured audit record
- No Capability Inference: Only explicit ACM entries count
- No APPROVE Path: Humans only, never agents
- No Mutation Without EXECUTE: READ/PROPOSE cannot mutate state
- No Drift: Enforcement logic references manifests directly
"""

from core.governance.acm_evaluator import ACMDecision, ACMEvaluator, DenialReason, EvaluationResult
from core.governance.acm_loader import ACMLoader, ACMLoadError, ACMValidationError

# PAC-BENSON-CTO-EXEC-CODY-IDENTITY-MODE-LAW-011: Identity & Mode Law Enforcement
from core.governance.gid_registry import (
    GID,
    Mode,
    AgentIdentity,
    GIDRegistry,
    GIDEnforcementError,
    UnknownGIDError,
    InvalidGIDFormatError,
    ModeNotPermittedError,
    LaneNotPermittedError,
    PACAuthorityError,
    format_echo_handshake,
    validate_echo_handshake,
    validate_agent_gid,
    validate_agent_mode,
    validate_agent_lane,
    validate_full_identity,
)
from core.governance.mode_schema import (
    ModeDeclaration,
    ModeSchemaError,
    MissingFieldError,
    MalformedFieldError,
    RoleMismatchError,
    ModeSchemaValidator,
    validate_mode_declaration,
    create_mode_declaration,
    extract_mode_from_pac,
)
from core.governance.tool_matrix import (
    ToolCategory,
    ToolMatrix,
    ToolMatrixResult,
    evaluate_tools,
    strip_disallowed_tools,
    is_tool_permitted,
    is_path_permitted,
)
from core.governance.wrap_validator import (
    ValidatedWRAP,
    WRAPValidationError,
    WRAPMissingBlockError,
    WRAPMalformedBlockError,
    WRAPIdentityError,
    WRAPProofError,
    WRAPSignatureError,
    WRAPValidator,
    validate_wrap,
    is_wrap_valid,
    check_ber_eligibility,
)
from core.governance.enforcement import (
    Enforcer,
    EnforcementContext,
    EnforcementError,
    EnforcementChainError,
    ToolDeniedError,
    PathDeniedError,
    EchoHandshakeError,
    get_enforcer,
    enforce,
    get_current_context,
    require_context,
    requires_enforcement,
    requires_mode,
    requires_lane,
)

# PAC-BENSON-EXEC-GOVERNANCE-TOOL-STRIP-ENFORCEMENT-014: Runtime Tool Enforcement
from core.governance.runtime_tool_enforcement import (
    RuntimeToolEnforcer,
    RuntimeToolRegistry,
    ToolExecutionRecord,
    RuntimeEnforcementError,
    ToolExecutionDenied,
    PathExecutionDenied,
    get_runtime_enforcer,
    reset_runtime_enforcer,
    enforced_runtime,
    tool_enforcement_session,
    runtime_tool_check,
    runtime_path_check,
)

# PAC-BENSON-EXEC-GOVERNANCE-TERMINAL-GATES-015: Terminal Gate Visibility
from core.governance.terminal_gates import (
    PASS_SYMBOL,
    FAIL_SYMBOL,
    PENDING_SYMBOL,
    SKIP_SYMBOL,
    BORDER_CHAR,
    BORDER_WIDTH,
    GateID,
    GateStatus,
    GATE_NAMES,
    GateResult,
    GateChecklistResult,
    TerminalGateRenderer,
    TerminalGateEvaluator,
    get_terminal_renderer,
    get_gate_evaluator,
    reset_terminal_renderer,
    emit_pac_ingest,
    emit_agent_dispatch,
    emit_wrap_receipt,
    emit_ber_approved,
    emit_ber_rejected,
    run_gate_checklist,
    # PAC-017: Orchestration Engine Emissions
    emit_orchestration_engine_engaged,
    emit_persona_authority_rejected,
    emit_system_governance_decision,
    emit_ber_authority_violation,
    emit_wrap_authority_violation,
    emit_self_approval_blocked,
)

# PAC-BENSON-EXEC-GOVERNANCE-ORCHESTRATION-ENGINE-RENAMING-017: System Identities
from core.governance.system_identities import (
    # Enums
    SystemIdentityType,
    # Classes
    SystemIdentity,
    SystemIdentityRegistry,
    # Canonical Identities
    ORCHESTRATION_ENGINE,
    EXECUTION_ENGINE,
    DRAFTING_SURFACE,
    # Exceptions
    SystemIdentityError,
    UnknownSystemIdentityError,
    BERAuthorityError,
    WRAPAuthorityError,
    PersonaAuthorityError,
    SelfApprovalError,
    # Validators
    validate_ber_authority,
    validate_wrap_authority,
    reject_persona_authority,
    validate_not_self_approval,
    # Convenience Functions
    get_orchestration_engine,
    get_execution_engine,
    get_drafting_surface,
    is_system_component,
    is_ber_authorized,
    is_wrap_authorized,
    # Invariants
    INVARIANTS as ORCHESTRATION_INVARIANTS,
    check_invariant_orc_001,
    check_invariant_orc_002,
    check_invariant_orc_003,
    check_invariant_orc_005,
)

# PAC-017: Enforcement Functions for System Identity
from core.governance.enforcement import (
    enforce_ber_authority,
    enforce_wrap_authority,
    enforce_no_self_approval,
    enforce_no_persona_authority,
    enforce_drafting_surface_cannot_govern,
)

# PAC-BENSON-EXEC-GOVERNANCE-BOOTSTRAP-PROTOCOL-016: Bootstrap & Session Reset
from core.governance.bootstrap_state import (
    BootstrapLock,
    BootstrapStatus,
    LOCK_NAMES,
    LockState,
    BootstrapState,
    BootstrapBuilder,
    BootstrapError,
    BootstrapRequiredError,
    BootstrapIncompleteError,
    BootstrapAlreadyStartedError,
    RebootstrapForbiddenError,
    LockAlreadyAcquiredError,
    BootstrapValidationError,
    get_current_session,
    set_current_session,
    clear_current_session,
    require_sealed_session,
)
from core.governance.bootstrap_enforcer import (
    BootstrapEnforcer,
    BootstrapTerminalRenderer,
    BootstrapResult,
    requires_bootstrap,
    bootstrap_session,
    get_bootstrap_enforcer,
    reset_bootstrap_enforcer,
    bootstrap,
    require_bootstrap_before_pac,
    is_session_bootstrapped,
)

# PAC-GOV-AUDIT-01: External Audit Export & Proof Bundle
from core.governance.audit_exporter import (
    AUDIT_BUNDLE_SCHEMA_VERSION,
    AuditBundleConfig,
    AuditBundleExporter,
    AuditBundleResult,
    export_audit_bundle,
)

# PAC-012: Governance Hardening — Schema & Semantics
from core.governance.governance_schema import (
    GOVERNANCE_SCHEMA_VERSION,
    # Acknowledgment
    AcknowledgmentStatus,
    AcknowledgmentType,
    AgentAcknowledgment,
    AcknowledgmentRegistry,
    get_acknowledgment_registry,
    reset_acknowledgment_registry,
    # Failure semantics
    FailureMode,
    RollbackStrategy,
    ExecutionOutcome,
    FailureSemantics,
    ExecutionFailure,
    # Non-capabilities
    CapabilityCategory,
    NonCapability,
    CANONICAL_NON_CAPABILITIES,
    # Human-in-the-loop
    HumanInterventionType,
    HumanBoundaryStatus,
    HumanBoundaryContract,
    HumanIntervention,
    # Violations
    GovernanceViolation,
)

# PAC-012: Governance Hardening — Dependency Graph & Causality
from core.governance.dependency_graph import (
    # Dependency types
    DependencyType,
    DependencyStatus,
    ArtifactType,
    # Dependency declaration
    ExecutionDependency,
    # Causality
    ArtifactReference,
    CausalityLink,
    # Failure propagation
    FailurePropagationMode,
    FailurePropagationRule,
    FailurePropagationEvent,
    # Graph
    DependencyGraph,
    # Registries
    CausalityRegistry,
    DependencyGraphRegistry,
    get_dependency_registry,
    get_causality_registry,
    reset_dependency_registry,
    reset_causality_registry,
)

# PAC-012: Governance Hardening — Retention & CI Gates
from core.governance.retention_policy import (
    RETENTION_SCHEMA_VERSION,
    # Retention
    RetentionPeriod,
    RETENTION_DAYS,
    ArtifactStorageType,
    RetentionPolicy,
    CANONICAL_RETENTION_POLICIES,
    # Training signals
    TrainingSignalClass,
    TrainingSignalDeclaration,
    # CI gates
    CIGateStatus,
    CIGateCheck,
    CIGateResult,
    GovernanceCIGate,
    run_ci_gate,
    # Registry
    RetentionRegistry,
    get_retention_registry,
    reset_retention_registry,
)
from core.governance.boot_checks import (
    BootCheckResult,
    GovernanceBootError,
    check_governance_boot,
    enforce_governance_boot,
    get_governance_files,
    get_governance_status,
    validate_governance_file,
)

# PAC-DAN-06: Persistent Denial Registry
from core.governance.denial_registry import (
    DEFAULT_DENIAL_DB_PATH,
    BaseDenialRegistry,
    DenialKey,
    DenialPersistenceError,
    InMemoryDenialRegistry,
    PersistentDenialRegistry,
    configure_denial_registry,
    get_persistent_denial_registry,
    is_persistent_mode,
    reset_persistent_denial_registry,
)
from core.governance.diggi_envelope_handler import (
    DIGGI_ALLOWED_VERBS,
    DIGGI_FORBIDDEN_VERBS,
    DIGGI_GID,
    CorrectionOption,
    DiggiCorrectionResponse,
    DiggiEnvelopeError,
    EnvelopeNotDenyError,
    ForbiddenVerbError,
    NoCorrectionAvailableError,
    can_diggi_handle,
    get_correction_for_reason,
    process_denial_envelope,
)
from core.governance.event_sink import (
    GovernanceEventEmitter,
    GovernanceEventSink,
    InMemorySink,
    JSONLFileSink,
    NullSink,
    configure_default_sink,
    emit_event,
    emitter,
)

# PAC-GOV-OBS-01: Governance Observability & Event Telemetry
from core.governance.events import (
    GovernanceEvent,
    GovernanceEventType,
    acm_evaluated_event,
    artifact_verification_event,
    decision_allowed_event,
    decision_denied_event,
    decision_escalated_event,
    diggi_correction_event,
    drcp_triggered_event,
    governance_boot_event,
    scope_violation_event,
    tool_execution_event,
)

# PAC-GOV-FRESHNESS-01: Trust Data Freshness Contract
from core.governance.freshness import (
    DEFAULT_MAX_STALENESS_SECONDS,
    FRESHNESS_MANIFEST_FILENAME,
    FRESHNESS_SCHEMA_VERSION,
    FreshnessManifest,
    FreshnessVerificationResult,
    SourceTimestamp,
    create_freshness_manifest,
    load_freshness_manifest,
    verify_freshness,
)
from core.governance.governance_fingerprint import (
    FINGERPRINT_VERSION,
    GOVERNANCE_ROOTS,
    FileHash,
    GovernanceDriftError,
    GovernanceFingerprint,
    GovernanceFingerprintEngine,
    GovernanceHashError,
    compute_governance_fingerprint,
    get_fingerprint_engine,
    get_governance_fingerprint,
    verify_governance_integrity,
)

# PAC-DAN-05: Governance Event Retention & Rotation
from core.governance.retention import (
    DEFAULT_ROTATING_LOG_PATH,
    MAX_FILE_COUNT,
    MAX_FILE_SIZE_BYTES,
    RETENTION_POLICY_VERSION,
    GovernanceEventExporter,
    RotatingJSONLSink,
    configure_rotating_sink,
    create_exporter,
)
from core.governance.telemetry import (
    emit_acm_evaluation,
    emit_artifact_verification,
    emit_diggi_correction,
    emit_drcp_triggered,
    emit_envelope_decision,
    emit_scope_violation,
    emit_tool_execution,
    safe_emit,
)

__all__ = [
    # ACM
    "ACMLoader",
    "ACMLoadError",
    "ACMValidationError",
    "ACMEvaluator",
    "ACMDecision",
    "EvaluationResult",
    "DenialReason",
    # Boot Checks (PAC-GOV-GUARD-01)
    "GovernanceBootError",
    "BootCheckResult",
    "enforce_governance_boot",
    "check_governance_boot",
    "validate_governance_file",
    "get_governance_files",
    "get_governance_status",
    # Diggi Envelope Handler (PAC-DIGGI-05)
    "DIGGI_GID",
    "DIGGI_FORBIDDEN_VERBS",
    "DIGGI_ALLOWED_VERBS",
    "CorrectionOption",
    "DiggiCorrectionResponse",
    "DiggiEnvelopeError",
    "EnvelopeNotDenyError",
    "NoCorrectionAvailableError",
    "ForbiddenVerbError",
    "process_denial_envelope",
    "can_diggi_handle",
    "get_correction_for_reason",
    # Governance Fingerprint (PAC-ALEX-02)
    "FINGERPRINT_VERSION",
    "GOVERNANCE_ROOTS",
    "FileHash",
    "GovernanceFingerprint",
    "GovernanceFingerprintEngine",
    "GovernanceHashError",
    "GovernanceDriftError",
    "compute_governance_fingerprint",
    "get_fingerprint_engine",
    "get_governance_fingerprint",
    "verify_governance_integrity",
    # Governance Events (PAC-GOV-OBS-01)
    "GovernanceEvent",
    "GovernanceEventType",
    "GovernanceEventEmitter",
    "GovernanceEventSink",
    "JSONLFileSink",
    "InMemorySink",
    "NullSink",
    "emit_event",
    "emitter",
    "configure_default_sink",
    # Event factories
    "acm_evaluated_event",
    "decision_allowed_event",
    "decision_denied_event",
    "decision_escalated_event",
    "drcp_triggered_event",
    "diggi_correction_event",
    "tool_execution_event",
    "artifact_verification_event",
    "scope_violation_event",
    "governance_boot_event",
    # Telemetry helpers
    "safe_emit",
    "emit_acm_evaluation",
    "emit_drcp_triggered",
    "emit_diggi_correction",
    "emit_tool_execution",
    "emit_artifact_verification",
    "emit_scope_violation",
    "emit_envelope_decision",
    # Retention & Export (PAC-DAN-05)
    "RETENTION_POLICY_VERSION",
    "MAX_FILE_SIZE_BYTES",
    "MAX_FILE_COUNT",
    "DEFAULT_ROTATING_LOG_PATH",
    "RotatingJSONLSink",
    "GovernanceEventExporter",
    "configure_rotating_sink",
    "create_exporter",
    # Audit Bundle Export (PAC-GOV-AUDIT-01)
    "AUDIT_BUNDLE_SCHEMA_VERSION",
    "AuditBundleConfig",
    "AuditBundleExporter",
    "AuditBundleResult",
    "export_audit_bundle",
    # Freshness Contract (PAC-GOV-FRESHNESS-01)
    "FRESHNESS_SCHEMA_VERSION",
    "FRESHNESS_MANIFEST_FILENAME",
    "DEFAULT_MAX_STALENESS_SECONDS",
    "FreshnessManifest",
    "FreshnessVerificationResult",
    "SourceTimestamp",
    "create_freshness_manifest",
    "load_freshness_manifest",
    "verify_freshness",
    # Persistent Denial Registry (PAC-DAN-06)
    "DEFAULT_DENIAL_DB_PATH",
    "BaseDenialRegistry",
    "DenialKey",
    "DenialPersistenceError",
    "InMemoryDenialRegistry",
    "PersistentDenialRegistry",
    "configure_denial_registry",
    "get_persistent_denial_registry",
    "is_persistent_mode",
    "reset_persistent_denial_registry",
    # Identity & Mode Law (PAC-BENSON-CTO-EXEC-CODY-IDENTITY-MODE-LAW-011)
    "GID",
    "Mode",
    "AgentIdentity",
    "GIDRegistry",
    "GIDEnforcementError",
    "UnknownGIDError",
    "InvalidGIDFormatError",
    "ModeNotPermittedError",
    "LaneNotPermittedError",
    "PACAuthorityError",
    "format_echo_handshake",
    "validate_echo_handshake",
    "validate_agent_gid",
    "validate_agent_mode",
    "validate_agent_lane",
    "validate_full_identity",
    "ModeDeclaration",
    "ModeSchemaError",
    "MissingFieldError",
    "MalformedFieldError",
    "RoleMismatchError",
    "ModeSchemaValidator",
    "validate_mode_declaration",
    "create_mode_declaration",
    "extract_mode_from_pac",
    "ToolCategory",
    "ToolMatrix",
    "ToolMatrixResult",
    "evaluate_tools",
    "strip_disallowed_tools",
    "is_tool_permitted",
    "is_path_permitted",
    "ValidatedWRAP",
    "WRAPValidationError",
    "WRAPMissingBlockError",
    "WRAPMalformedBlockError",
    "WRAPIdentityError",
    "WRAPProofError",
    "WRAPSignatureError",
    "WRAPValidator",
    "validate_wrap",
    "is_wrap_valid",
    "check_ber_eligibility",
    "Enforcer",
    "EnforcementContext",
    "EnforcementError",
    "EnforcementChainError",
    "ToolDeniedError",
    "PathDeniedError",
    "EchoHandshakeError",
    "get_enforcer",
    "enforce",
    "get_current_context",
    "require_context",
    "requires_enforcement",
    "requires_mode",
    "requires_lane",
    # Runtime Tool Enforcement (PAC-BENSON-EXEC-GOVERNANCE-TOOL-STRIP-ENFORCEMENT-014)
    "RuntimeToolEnforcer",
    "RuntimeToolRegistry",
    "ToolExecutionRecord",
    "RuntimeEnforcementError",
    "ToolExecutionDenied",
    "PathExecutionDenied",
    "get_runtime_enforcer",
    "reset_runtime_enforcer",
    "enforced_runtime",
    "tool_enforcement_session",
    "runtime_tool_check",
    "runtime_path_check",
    # Terminal Gate Visibility (PAC-BENSON-EXEC-GOVERNANCE-TERMINAL-GATES-015)
    "PASS_SYMBOL",
    "FAIL_SYMBOL",
    "PENDING_SYMBOL",
    "SKIP_SYMBOL",
    "BORDER_CHAR",
    "BORDER_WIDTH",
    "GateID",
    "GateStatus",
    "GATE_NAMES",
    "GateResult",
    "GateChecklistResult",
    "TerminalGateRenderer",
    "TerminalGateEvaluator",
    "get_terminal_renderer",
    "get_gate_evaluator",
    "reset_terminal_renderer",
    "emit_pac_ingest",
    "emit_agent_dispatch",
    "emit_wrap_receipt",
    "emit_ber_approved",
    "emit_ber_rejected",
    "run_gate_checklist",
    # Bootstrap Protocol (PAC-BENSON-EXEC-GOVERNANCE-BOOTSTRAP-PROTOCOL-016)
    "BootstrapLock",
    "BootstrapStatus",
    "LOCK_NAMES",
    "LockState",
    "BootstrapState",
    "BootstrapBuilder",
    "BootstrapError",
    "BootstrapRequiredError",
    "BootstrapIncompleteError",
    "BootstrapAlreadyStartedError",
    "RebootstrapForbiddenError",
    "LockAlreadyAcquiredError",
    "BootstrapValidationError",
    "get_current_session",
    "set_current_session",
    "clear_current_session",
    "require_sealed_session",
    "BootstrapEnforcer",
    "BootstrapTerminalRenderer",
    "BootstrapResult",
    "requires_bootstrap",
    "bootstrap_session",
    "get_bootstrap_enforcer",
    "reset_bootstrap_enforcer",
    "bootstrap",
    "require_bootstrap_before_pac",
    "is_session_bootstrapped",
    # PAC-012: Governance Schema
    "GOVERNANCE_SCHEMA_VERSION",
    "AcknowledgmentStatus",
    "AcknowledgmentType",
    "AgentAcknowledgment",
    "AcknowledgmentRegistry",
    "get_acknowledgment_registry",
    "reset_acknowledgment_registry",
    "FailureMode",
    "RollbackStrategy",
    "ExecutionOutcome",
    "FailureSemantics",
    "ExecutionFailure",
    "CapabilityCategory",
    "NonCapability",
    "CANONICAL_NON_CAPABILITIES",
    "HumanInterventionType",
    "HumanBoundaryStatus",
    "HumanBoundaryContract",
    "HumanIntervention",
    "GovernanceViolation",
    # PAC-012: Dependency Graph
    "DependencyType",
    "DependencyStatus",
    "ArtifactType",
    "ExecutionDependency",
    "ArtifactReference",
    "CausalityLink",
    "FailurePropagationMode",
    "FailurePropagationRule",
    "FailurePropagationEvent",
    "DependencyGraph",
    "CausalityRegistry",
    "DependencyGraphRegistry",
    "get_dependency_registry",
    "get_causality_registry",
    "reset_dependency_registry",
    "reset_causality_registry",
    # PAC-012: Retention Policy
    "RETENTION_SCHEMA_VERSION",
    "RetentionPeriod",
    "RETENTION_DAYS",
    "ArtifactStorageType",
    "RetentionPolicy",
    "CANONICAL_RETENTION_POLICIES",
    "TrainingSignalClass",
    "TrainingSignalDeclaration",
    "CIGateStatus",
    "CIGateCheck",
    "CIGateResult",
    "GovernanceCIGate",
    "run_ci_gate",
    "RetentionRegistry",
    "get_retention_registry",
    "reset_retention_registry",
]
