/**
 * Mock Data for Operator Console
 *
 * Fallback data when backend is unavailable.
 */

import type { OperatorQueueItem, OperatorSummary } from "../types/chainbridge";

export const MOCK_OPERATOR_SUMMARY: OperatorSummary = {
  totalAtRisk: 12,
  criticalCount: 3,
  highCount: 9,
  needsSnapshotCount: 5,
  paymentHoldsCount: 2,
  lastUpdatedAt: new Date().toISOString(),
};

export const MOCK_OPERATOR_QUEUE: OperatorQueueItem[] = [
  {
    shipmentId: "SHP-2025-001",
    riskLevel: "CRITICAL",
    riskScore: 92,
    corridorCode: "CN-US-WEST",
    mode: "OCEAN",
    incoterm: "FOB",
    completeness_pct: 45,
    blocking_gap_count: 3,
    template_name: "Electronics Standard",
    days_delayed: 5,
    latestSnapshotStatus: "FAILED",
    latest_snapshot_updatedAt: new Date(Date.now() - 3600000).toISOString(),
    needs_snapshot: true,
    has_payment_hold: true,
    last_event_at: new Date().toISOString(),
    recon_state: "BLOCKED_DISPUTE",
    reconScore: 45,
    approvedAmount: 0,
    heldAmount: 150000,
    has_ricardian_wrapper: true,
    ricardian_status: "FROZEN",
    supremacyEnabled: true,
    materialAdverseOverride: false,
    declared_valueUsd: 150000
  },
  {
    shipmentId: "SHP-2025-002",
    riskLevel: "CRITICAL",
    riskScore: 88,
    corridorCode: "VN-US-EAST",
    mode: "AIR",
    incoterm: "DDP",
    completeness_pct: 60,
    blocking_gap_count: 2,
    template_name: "Pharma Cold Chain",
    days_delayed: 2,
    latestSnapshotStatus: "PENDING",
    latest_snapshot_updatedAt: new Date(Date.now() - 7200000).toISOString(),
    needs_snapshot: true,
    has_payment_hold: false,
    last_event_at: new Date().toISOString(),
    recon_state: "PARTIAL_ESCROW",
    reconScore: 72,
    approvedAmount: 50000,
    heldAmount: 25000,
    has_ricardian_wrapper: true,
    ricardian_status: "ACTIVE",
    supremacyEnabled: true,
    materialAdverseOverride: false,
    declared_valueUsd: 75000
  },
  {
    shipmentId: "SHP-2025-003",
    riskLevel: "CRITICAL",
    riskScore: 85,
    corridorCode: "IN-EU-NORTH",
    mode: "OCEAN",
    incoterm: "CIF",
    completeness_pct: 30,
    blocking_gap_count: 4,
    template_name: "Textiles Bulk",
    days_delayed: 12,
    latestSnapshotStatus: "SUCCESS",
    latest_snapshot_updatedAt: new Date(Date.now() - 86400000).toISOString(),
    needs_snapshot: false,
    has_payment_hold: true,
    last_event_at: new Date().toISOString(),
    recon_state: "CLEAN",
    reconScore: 95,
    approvedAmount: 45000,
    heldAmount: 0,
    has_ricardian_wrapper: false,
    ricardian_status: null,
    supremacyEnabled: false,
    materialAdverseOverride: null,
    declared_valueUsd: 45000
  },
  {
    shipmentId: "SHP-2025-004",
    riskLevel: "HIGH",
    riskScore: 78,
    corridorCode: "CN-US-WEST",
    mode: "OCEAN",
    incoterm: "FOB",
    completeness_pct: 75,
    blocking_gap_count: 1,
    template_name: "Consumer Electronics",
    days_delayed: 0,
    latestSnapshotStatus: "SUCCESS",
    latest_snapshot_updatedAt: new Date(Date.now() - 14400000).toISOString(),
    needs_snapshot: false,
    has_payment_hold: false,
    last_event_at: new Date().toISOString(),
    recon_state: "CLEAN",
    reconScore: 98,
    approvedAmount: 220000,
    heldAmount: 0,
    has_ricardian_wrapper: true,
    ricardian_status: "ACTIVE",
    supremacyEnabled: true,
    materialAdverseOverride: false,
    declared_valueUsd: 220000
  },
  {
    shipmentId: "SHP-2025-005",
    riskLevel: "HIGH",
    riskScore: 75,
    corridorCode: "MX-US-SOUTH",
    mode: "TRUCK_FTL",
    incoterm: "DAP",
    completeness_pct: 80,
    blocking_gap_count: 1,
    template_name: "Auto Parts",
    days_delayed: 1,
    latestSnapshotStatus: "IN_PROGRESS",
    latest_snapshot_updatedAt: new Date(Date.now() - 1800000).toISOString(),
    needs_snapshot: false,
    has_payment_hold: false,
    last_event_at: new Date().toISOString(),
    recon_state: "CLEAN",
    reconScore: 92,
    approvedAmount: 85000,
    heldAmount: 0,
    has_ricardian_wrapper: true,
    ricardian_status: "ACTIVE",
    supremacyEnabled: false,
    materialAdverseOverride: null,
    declared_valueUsd: 85000
  }
];
