import { RiskEvaluationRecord } from "./types";

export const mockRiskEvaluations: RiskEvaluationRecord[] = [
  {
    evaluation_id: "eval_001",
    timestamp: "2025-12-06T08:30:00Z",
    model_version: "chainiq_v1_maggie",
    shipment_id: "SHP-1001",
    carrier_id: "CARR-DHL",
    lane_id: "US-MX",
    risk_score: 85,
    risk_band: "HIGH",
    primary_reasons: ["High Value (>$100k)", "Border Crossing Risk", "IoT Alert Spike"],
    features_snapshot: {
      value_usd: 150000,
      is_hazmat: false,
      is_temp_control: true,
      iot_alert_count: 5,
      recent_delay_events: 2,
      lane_risk_index: 0.8,
      border_crossing_count: 1,
      carrier_incident_rate_90d: 0.05,
      carrier_tenure_days: 1200,
    },
  },
  {
    evaluation_id: "eval_002",
    timestamp: "2025-12-06T09:15:00Z",
    model_version: "chainiq_v1_maggie",
    shipment_id: "SHP-1002",
    carrier_id: "CARR-FEDEX",
    lane_id: "US-CA",
    risk_score: 45,
    risk_band: "MEDIUM",
    primary_reasons: ["Temp Control Required", "Minor Lane Congestion"],
    features_snapshot: {
      value_usd: 45000,
      is_hazmat: false,
      is_temp_control: true,
      iot_alert_count: 0,
      recent_delay_events: 1,
      lane_risk_index: 0.4,
      border_crossing_count: 1,
      carrier_incident_rate_90d: 0.01,
      carrier_tenure_days: 3500,
    },
  },
  {
    evaluation_id: "eval_003",
    timestamp: "2025-12-06T09:45:00Z",
    model_version: "chainiq_v1_maggie",
    shipment_id: "SHP-1003",
    carrier_id: "CARR-UPS",
    lane_id: "US-US-EAST",
    risk_score: 12,
    risk_band: "LOW",
    primary_reasons: [],
    features_snapshot: {
      value_usd: 5000,
      is_hazmat: false,
      is_temp_control: false,
      iot_alert_count: 0,
      recent_delay_events: 0,
      lane_risk_index: 0.1,
      border_crossing_count: 0,
      carrier_incident_rate_90d: 0.00,
      carrier_tenure_days: 5000,
    },
  },
  {
    evaluation_id: "eval_004",
    timestamp: "2025-12-06T10:00:00Z",
    model_version: "chainiq_v1_maggie",
    shipment_id: "SHP-1004",
    carrier_id: "CARR-XPO",
    lane_id: "US-MX",
    risk_score: 92,
    risk_band: "HIGH",
    primary_reasons: ["Hazmat Shipment", "Carrier Incident History", "High Lane Risk"],
    features_snapshot: {
      value_usd: 85000,
      is_hazmat: true,
      is_temp_control: false,
      iot_alert_count: 2,
      recent_delay_events: 3,
      lane_risk_index: 0.9,
      border_crossing_count: 1,
      carrier_incident_rate_90d: 0.12,
      carrier_tenure_days: 180,
    },
  },
  {
    evaluation_id: "eval_005",
    timestamp: "2025-12-06T10:30:00Z",
    model_version: "chainiq_v1_maggie",
    shipment_id: "SHP-1005",
    carrier_id: "CARR-DHL",
    lane_id: "EU-US",
    risk_score: 35,
    risk_band: "MEDIUM",
    primary_reasons: ["International Transit", "Value > $20k"],
    features_snapshot: {
      value_usd: 25000,
      is_hazmat: false,
      is_temp_control: false,
      iot_alert_count: 0,
      recent_delay_events: 0,
      lane_risk_index: 0.3,
      border_crossing_count: 1,
      carrier_incident_rate_90d: 0.02,
      carrier_tenure_days: 1200,
    },
  },
  {
    evaluation_id: "eval_006",
    timestamp: "2025-12-06T11:00:00Z",
    model_version: "chainiq_v1_maggie",
    shipment_id: "SHP-1006",
    carrier_id: "CARR-USPS",
    lane_id: "US-US-WEST",
    risk_score: 5,
    risk_band: "LOW",
    primary_reasons: [],
    features_snapshot: {
      value_usd: 1200,
      is_hazmat: false,
      is_temp_control: false,
      iot_alert_count: 0,
      recent_delay_events: 0,
      lane_risk_index: 0.05,
      border_crossing_count: 0,
      carrier_incident_rate_90d: 0.00,
      carrier_tenure_days: 8000,
    },
  },
];
