/**
 * AuditPackView - Audit Pack Display Component
 *
 * Renders the AuditPack response as structured cards with:
 * - Auto-audit metadata
 * - Core settlement summary
 * - Proof verification status
 * - Risk summary with snapshots
 * - SLA/IoT summaries
 * - Document availability
 * - Event timeline snippet
 * - Raw JSON viewer
 */

import { AlertTriangle, CheckCircle, Clock, Download, ExternalLink, FileText, Shield, XCircle, Zap } from "lucide-react";

import type { AuditPackResponse, ReconciliationSummary } from "../../types/backend";
import { classNames } from "../../utils/classNames";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/Card";

interface AuditPackViewProps {
  audit: AuditPackResponse;
  reconciliation?: ReconciliationSummary | null;
}

/**
 * Download AuditPack as JSON file
 */
function downloadAuditPack(audit: AuditPackResponse) {
  const blob = new Blob([JSON.stringify(audit, null, 2)], {
    type: "application/json",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `auditpack-${audit.settlementId}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

export function AuditPackView({ audit, reconciliation }: AuditPackViewProps) {
  return (
    <div className="space-y-4">
      {/* Header with metadata */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-sm font-medium text-slate-200">
            AuditPack v1 <span className="text-slate-500">(virtual)</span>
          </h3>
          <p className="text-xs text-slate-400 mt-0.5">
            Generated {new Date(audit.generatedAt).toLocaleString()}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {audit.auditMetadata.autoGenerated && (
            <div className="flex flex-col items-end gap-1">
              <span className="inline-flex items-center gap-1 px-2 py-1 bg-emerald-500/10 text-emerald-400 text-xs font-medium rounded border border-emerald-500/30">
                ✓ Auto audit
              </span>
              {audit.auditMetadata.triggeredByRules.length > 0 && (
                <span className="text-xs text-slate-500">
                  Rules: {audit.auditMetadata.triggeredByRules.join(", ")}
                </span>
              )}
            </div>
          )}
          <button
            onClick={() => downloadAuditPack(audit)}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-slate-700 hover:bg-slate-600 text-slate-200 text-xs font-medium rounded transition-colors"
          >
            <Download className="h-3.5 w-3.5" />
            Download JSON
          </button>
        </div>
      </div>

      {/* Summary Cards Row */}
      <div className="grid grid-cols-2 gap-3">
        {/* Core Summary */}
        <Card className="bg-slate-800/30 border-slate-700">
          <CardHeader className="pb-2">
            <CardTitle className="text-xs text-slate-400">Core Settlement</CardTitle>
          </CardHeader>
          <CardContent className="space-y-1.5 text-xs">
            {audit.core.amount && (
              <div className="flex justify-between">
                <span className="text-slate-400">Amount</span>
                <span className="font-mono font-medium text-slate-200">
                  {audit.core.currency || "USD"} {audit.core.amount.toFixed(2)}
                </span>
              </div>
            )}
            {audit.core.state && (
              <div className="flex justify-between">
                <span className="text-slate-400">State</span>
                <span
                  className={classNames(
                    "font-medium",
                    audit.core.state === "PAID"
                      ? "text-emerald-400"
                      : audit.core.state === "DISPUTED"
                      ? "text-rose-400"
                      : "text-slate-300"
                  )}
                >
                  {audit.core.state}
                </span>
              </div>
            )}
            {audit.core.lane?.corridor && (
              <div className="flex justify-between">
                <span className="text-slate-400">Corridor</span>
                <span className="text-slate-200">{audit.core.lane.corridor}</span>
              </div>
            )}
            {audit.core.lane && (
              <div className="flex justify-between">
                <span className="text-slate-400">Lane</span>
                <span className="text-slate-200 text-right">
                  {audit.core.lane.originCity || audit.core.lane.originCountry || "?"} →{" "}
                  {audit.core.lane.destinationCity || audit.core.lane.destinationCountry || "?"}
                </span>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Proof Summary */}
        <Card className="bg-slate-800/30 border-slate-700">
          <CardHeader className="pb-2">
            <CardTitle className="text-xs text-slate-400">Proof Verification</CardTitle>
          </CardHeader>
          <CardContent className="space-y-1.5 text-xs">
            <div className="flex justify-between items-center">
              <span className="text-slate-400">Status</span>
              <span
                className={classNames(
                  "inline-flex items-center gap-1 font-medium",
                  audit.proofSummary.status === "VERIFIED"
                    ? "text-emerald-400"
                    : audit.proofSummary.status === "FAILED"
                    ? "text-rose-400"
                    : audit.proofSummary.status === "PENDING"
                    ? "text-amber-400"
                    : "text-slate-500"
                )}
              >
                {audit.proofSummary.status === "VERIFIED" && <CheckCircle className="h-3 w-3" />}
                {audit.proofSummary.status === "FAILED" && <XCircle className="h-3 w-3" />}
                {audit.proofSummary.status === "PENDING" && <Clock className="h-3 w-3" />}
                {audit.proofSummary.status}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-400">Provider</span>
              <span className="text-slate-200">{audit.proofSummary.provider}</span>
            </div>
            {audit.proofSummary.intentHash && (
              <div className="flex justify-between">
                <span className="text-slate-400">Intent Hash</span>
                <span className="font-mono text-xs text-slate-300">
                  {audit.proofSummary.intentHash.slice(0, 12)}...
                </span>
              </div>
            )}
            {audit.proofSummary.lastVerifiedAt && (
              <div className="flex justify-between">
                <span className="text-slate-400">Verified</span>
                <span className="text-slate-300">
                  {new Date(audit.proofSummary.lastVerifiedAt).toLocaleDateString()}
                </span>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Risk Summary */}
        <Card className="bg-slate-800/30 border-slate-700">
          <CardHeader className="pb-2">
            <CardTitle className="text-xs text-slate-400">Risk Summary</CardTitle>
          </CardHeader>
          <CardContent className="space-y-1.5 text-xs">
            {audit.riskSummary.latestScore !== null && (
              <div className="flex justify-between">
                <span className="text-slate-400">Latest Score</span>
                <span className="font-bold text-slate-200">{audit.riskSummary.latestScore}</span>
              </div>
            )}
            {audit.riskSummary.latestBand && (
              <div className="flex justify-between">
                <span className="text-slate-400">Band</span>
                <span
                  className={classNames(
                    "font-medium",
                    audit.riskSummary.latestBand === "CRITICAL"
                      ? "text-rose-400"
                      : audit.riskSummary.latestBand === "HIGH"
                      ? "text-amber-400"
                      : "text-emerald-400"
                  )}
                >
                  {audit.riskSummary.latestBand}
                </span>
              </div>
            )}
            {audit.riskSummary.engineMode && (
              <div className="flex justify-between">
                <span className="text-slate-400">Engine Mode</span>
                <span className="text-slate-200">{audit.riskSummary.engineMode}</span>
              </div>
            )}
            <div className="flex justify-between">
              <span className="text-slate-400">Snapshots</span>
              <span className="text-slate-200">{audit.riskSummary.snapshots.length}</span>
            </div>
          </CardContent>
        </Card>

        {/* SLA/IoT Summary */}
        <Card className="bg-slate-800/30 border-slate-700">
          <CardHeader className="pb-2">
            <CardTitle className="text-xs text-slate-400">SLA & IoT</CardTitle>
          </CardHeader>
          <CardContent className="space-y-1.5 text-xs">
            {audit.slaSummary && (
              <>
                {audit.slaSummary.slaBand && (
                  <div className="flex justify-between">
                    <span className="text-slate-400">SLA Band</span>
                    <span className="text-slate-200">{audit.slaSummary.slaBand}</span>
                  </div>
                )}
                {audit.slaSummary.breach !== null && (
                  <div className="flex justify-between items-center">
                    <span className="text-slate-400">Breach</span>
                    <span
                      className={classNames(
                        "font-medium",
                        audit.slaSummary.breach ? "text-rose-400" : "text-emerald-400"
                      )}
                    >
                      {audit.slaSummary.breach ? "YES" : "NO"}
                    </span>
                  </div>
                )}
              </>
            )}
            {audit.iotSummary && (
              <>
                {audit.iotSummary.hasIot && (
                  <div className="flex justify-between">
                    <span className="text-slate-400">IoT Enabled</span>
                    <span className="text-emerald-400">✓</span>
                  </div>
                )}
                {audit.iotSummary.alertsCount !== null &&
                 audit.iotSummary.alertsCount !== undefined &&
                 audit.iotSummary.alertsCount > 0 && (
                  <div className="flex justify-between">
                    <span className="text-slate-400">Alerts</span>
                    <span className="text-amber-400">{audit.iotSummary.alertsCount}</span>
                  </div>
                )}
              </>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Micro-Settlement Summary (R01) */}
      {reconciliation && (
        <Card className="bg-gradient-to-br from-slate-800/40 to-slate-800/20 border-emerald-700/50">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm text-slate-200">Micro-Settlement</CardTitle>
              <span
                className={classNames(
                  "px-3 py-1 rounded text-xs font-bold",
                  reconciliation.decision === "AUTO_APPROVE"
                    ? "bg-emerald-900/50 text-emerald-300 border border-emerald-700/50"
                    : reconciliation.decision === "PARTIAL_APPROVE"
                    ? "bg-amber-900/50 text-amber-300 border border-amber-700/50"
                    : "bg-rose-900/50 text-rose-300 border border-rose-700/50"
                )}
              >
                {reconciliation.decision === "AUTO_APPROVE"
                  ? "Auto-approved"
                  : reconciliation.decision === "PARTIAL_APPROVE"
                  ? "Partial"
                  : "Blocked"}
              </span>
            </div>
          </CardHeader>
          <CardContent className="space-y-3 text-xs">
            <div className="grid grid-cols-3 gap-3">
              <div className="p-2 bg-emerald-950/30 border border-emerald-700/50 rounded">
                <div className="text-emerald-400 mb-1">Approved</div>
                <div className="text-lg font-mono font-bold text-emerald-300">
                  ${reconciliation.approvedAmount.toFixed(2)}
                </div>
              </div>
              <div className="p-2 bg-amber-950/30 border border-amber-700/50 rounded">
                <div className="text-amber-400 mb-1">Held</div>
                <div className="text-lg font-mono font-bold text-amber-300">
                  ${reconciliation.heldAmount.toFixed(2)}
                </div>
              </div>
              <div className="p-2 bg-slate-700/30 border border-slate-600 rounded">
                <div className="text-slate-400 mb-1">Score</div>
                <div className="text-lg font-mono font-bold text-slate-200">
                  {reconciliation.reconScore}/100
                </div>
              </div>
            </div>

            {reconciliation.flags.length > 0 && (
              <div className="pt-2 border-t border-slate-700">
                <div className="text-slate-400 mb-1.5">Adjustments</div>
                <div className="flex flex-wrap gap-1">
                  {reconciliation.flags.map((flag, idx) => (
                    <span
                      key={idx}
                      className="px-1.5 py-0.5 bg-blue-900/30 text-blue-300 border border-blue-700/50 rounded text-xs"
                    >
                      {flag.replace(/_/g, " ")}
                    </span>
                  ))}
                </div>
              </div>
            )}

            <div className="pt-2 border-t border-slate-700">
              <a
                href="#reconciliation"
                onClick={(e) => {
                  e.preventDefault();
                  // Trigger tab switch to reconciliation
                  const event = new CustomEvent("switchToReconciliation");
                  window.dispatchEvent(event);
                }}
                className="text-emerald-400 hover:text-emerald-300 text-xs font-medium inline-flex items-center gap-1 transition-colors"
              >
                View reconciliation details →
              </a>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Legal Wrapper Section (LEGAL-R01) */}
      {audit.legalWrapper && (
        <Card className="bg-gradient-to-br from-slate-800/40 to-slate-800/20 border-emerald-700/50">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Shield className="h-4 w-4 text-emerald-400" />
                <CardTitle className="text-sm text-slate-200">Legal Wrapper (Ricardian Contract)</CardTitle>
              </div>
              <span
                className={classNames(
                  "px-2 py-1 rounded text-xs font-bold",
                  audit.legalWrapper.status === "ACTIVE"
                    ? "bg-emerald-900/50 text-emerald-300 border border-emerald-700/50"
                    : audit.legalWrapper.status === "FROZEN"
                    ? "bg-rose-900/50 text-rose-300 border border-rose-700/50"
                    : "bg-slate-700 text-slate-300 border border-slate-600"
                )}
              >
                {audit.legalWrapper.status}
              </span>
            </div>
          </CardHeader>
          <CardContent className="space-y-2 text-xs">
            <div className="grid grid-cols-2 gap-2">
              <div>
                <span className="text-slate-400">Instrument:</span>
                <span className="ml-2 text-slate-200">
                  {audit.legalWrapper.instrumentType.replace(/_/g, " ")}
                </span>
              </div>
              <div>
                <span className="text-slate-400">Reference:</span>
                <span className="ml-2 font-mono text-slate-200 text-xs">
                  {audit.legalWrapper.physicalReference}
                </span>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-2">
              <div>
                <span className="text-slate-400">Governing Law:</span>
                <span className="ml-2 text-slate-200">{audit.legalWrapper.governingLaw}</span>
              </div>
              <div>
                <span className="text-slate-400">Version:</span>
                <span className="ml-2 font-mono text-slate-200">
                  {audit.legalWrapper.ricardianVersion}
                </span>
              </div>
            </div>

            <div className="pt-2 border-t border-slate-700">
              <div className="text-slate-400 mb-1">Document Hash:</div>
              <div className="font-mono text-xs text-slate-300">
                {audit.legalWrapper.pdfHash.slice(0, 24)}...{audit.legalWrapper.pdfHash.slice(-12)}
              </div>
            </div>

            {audit.legalWrapper.smartContractChain && audit.legalWrapper.smartContractAddress && (
              <div className="pt-2 border-t border-slate-700">
                <div className="text-slate-400 mb-1">Smart Contract:</div>
                <div className="text-slate-200">{audit.legalWrapper.smartContractChain}</div>
                <div className="font-mono text-xs text-slate-300 mt-0.5">
                  {audit.legalWrapper.smartContractAddress.slice(0, 12)}...
                  {audit.legalWrapper.smartContractAddress.slice(-8)}
                </div>
              </div>
            )}

            <div className="flex gap-2 pt-2">
              <a
                href={audit.legalWrapper.pdfUri}
                target="_blank"
                rel="noopener noreferrer"
                className="flex-1 inline-flex items-center justify-center gap-1 px-2 py-1.5 bg-emerald-900/30 hover:bg-emerald-900/50 text-emerald-300 text-xs font-medium rounded border border-emerald-700/50 transition-colors"
              >
                <ExternalLink className="h-3 w-3" />
                View Legal PDF
              </a>
              {audit.legalWrapper.smartContractChain && audit.legalWrapper.smartContractAddress && (
                <a
                  href="#"
                  onClick={(e) => {
                    e.preventDefault();
                    // TODO: Map chain to explorer URL
                  }}
                  className="inline-flex items-center justify-center gap-1 px-2 py-1.5 bg-slate-700 hover:bg-slate-600 text-slate-300 text-xs font-medium rounded transition-colors"
                >
                  <ExternalLink className="h-3 w-3" />
                  View on Chain
                </a>
              )}
            </div>

            {audit.legalWrapper.status === "FROZEN" && audit.legalWrapper.freezeReason && (
              <div className="pt-2 border-t border-rose-700/50">
                <div className="p-2 bg-rose-950/30 border border-rose-700/50 rounded">
                  <div className="flex items-start gap-1.5">
                    <AlertTriangle className="h-3.5 w-3.5 text-rose-400 mt-0.5 flex-shrink-0" />
                    <div>
                      <div className="text-xs font-bold text-rose-300 mb-0.5">Legal Freeze:</div>
                      <div className="text-xs text-rose-200">
                        This asset is under legal freeze. Movement and settlement may be restricted.
                      </div>
                      <div className="text-xs text-rose-300 mt-1">Reason: {audit.legalWrapper.freezeReason}</div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Digital Supremacy Compliance Section - SONNY PACK */}
      {audit.legalWrapper && (
        <Card className="bg-gradient-to-br from-slate-800/40 to-slate-800/20 border-purple-700/50">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Zap className="h-4 w-4 text-purple-400" />
                <CardTitle className="text-sm text-slate-200">Digital Supremacy Compliance</CardTitle>
              </div>
              <span
                className={classNames(
                  "px-2 py-1 rounded text-xs font-bold",
                  audit.legalWrapper.materialAdverseOverride
                    ? "bg-rose-900/50 text-rose-300 border border-rose-700/50"
                    : audit.legalWrapper.supremacyEnabled
                    ? "bg-purple-900/50 text-purple-300 border border-purple-700/50"
                    : "bg-slate-700 text-slate-400 border border-slate-600"
                )}
              >
                {audit.legalWrapper.materialAdverseOverride
                  ? "OVERRIDDEN"
                  : audit.legalWrapper.supremacyEnabled
                  ? "ENABLED"
                  : "DISABLED"}
              </span>
            </div>
          </CardHeader>
          <CardContent className="space-y-3 text-xs">
            {audit.legalWrapper.materialAdverseOverride ? (
              // Kill Switch Active
              <div className="p-3 bg-rose-950/30 border border-rose-700/50 rounded">
                <div className="flex items-start gap-2">
                  <AlertTriangle className="h-4 w-4 text-rose-400 mt-0.5 flex-shrink-0" />
                  <div className="space-y-2">
                    <div className="text-sm font-bold text-rose-300">
                      🚨 Material Adverse Exception Triggered
                    </div>
                    <div className="text-xs text-rose-200">
                      Digital Supremacy has been suspended. Smart Contract execution is NOT authoritative.
                    </div>
                    {audit.legalWrapper.freezeReason && (
                      <div className="text-xs text-rose-300 pt-2 border-t border-rose-700/50">
                        <span className="font-semibold">Reason:</span> {audit.legalWrapper.freezeReason}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            ) : audit.legalWrapper.supremacyEnabled ? (
              // Supremacy Enabled
              <>
                <div className="space-y-2">
                  <div className="flex items-center gap-2 text-purple-300">
                    <CheckCircle className="h-3.5 w-3.5" />
                    <span className="font-semibold">Code Prevails Over Prose</span>
                  </div>
                  {audit.legalWrapper.ricardianMetadata?.digitalSupremacy && (
                    <>
                      {/* Governing Law Blocks */}
                      <div className="grid grid-cols-2 gap-2 pt-2 border-t border-slate-700">
                        <div>
                          <div className="text-slate-400 mb-1">Legal Framework:</div>
                          <div className="space-y-1">
                            <div className="flex items-center gap-1.5 text-emerald-300">
                              <CheckCircle className="h-3 w-3" />
                              <span className="text-xs">
                                {audit.legalWrapper.ricardianMetadata.digitalSupremacy.uccReference}
                              </span>
                            </div>
                            {audit.legalWrapper.ricardianMetadata.digitalSupremacy.ukEtda2023 && (
                              <div className="flex items-center gap-1.5 text-emerald-300">
                                <CheckCircle className="h-3 w-3" />
                                <span className="text-xs">UK ETDA 2023</span>
                              </div>
                            )}
                          </div>
                        </div>
                        <div>
                          <div className="text-slate-400 mb-1">Precedence:</div>
                          <div className="text-purple-300 font-semibold text-xs">
                            {audit.legalWrapper.ricardianMetadata.digitalSupremacy.precedence
                              .replace(/_/g, " ")
                              .toUpperCase()}
                          </div>
                        </div>
                      </div>

                      {/* Hash Binding */}
                      <div className="pt-2 border-t border-slate-700">
                        <div className="text-slate-400 mb-1">📎 Hash Binding:</div>
                        <div className="font-mono text-xs text-slate-300 bg-slate-900/50 p-2 rounded">
                          {audit.legalWrapper.ricardianMetadata.digitalSupremacy.hashBinding.slice(0, 32)}...
                          {audit.legalWrapper.ricardianMetadata.digitalSupremacy.hashBinding.slice(-16)}
                        </div>
                      </div>

                      {/* Kill Switch Conditions */}
                      {audit.legalWrapper.ricardianMetadata.digitalSupremacy.killSwitch.enabled && (
                        <div className="pt-2 border-t border-slate-700">
                          <div className="text-slate-400 mb-2">⚙️ Kill Switch Conditions:</div>
                          <div className="space-y-1">
                            {audit.legalWrapper.ricardianMetadata.digitalSupremacy.killSwitch.conditions.map(
                              (condition, idx) => (
                                <div
                                  key={idx}
                                  className="flex items-start gap-2 p-2 bg-slate-900/50 border border-slate-700 rounded"
                                >
                                  <span className="text-amber-400 font-bold">⚠</span>
                                  <span className="text-slate-300 text-xs">{condition}</span>
                                </div>
                              )
                            )}
                          </div>
                        </div>
                      )}
                    </>
                  )}
                </div>
              </>
            ) : (
              // Supremacy Disabled
              <div className="p-3 bg-amber-950/20 border border-amber-700/50 rounded">
                <div className="flex items-start gap-2">
                  <AlertTriangle className="h-4 w-4 text-amber-400 mt-0.5 flex-shrink-0" />
                  <div className="space-y-1">
                    <div className="text-sm font-semibold text-amber-300">Code–Prose Parity</div>
                    <div className="text-xs text-slate-300">
                      This instrument does NOT prioritize executable code over contract text.
                    </div>
                    <div className="text-xs text-amber-400 font-medium pt-1">
                      ⚠️ Reduced bankability
                    </div>
                  </div>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Documents Section */}
      <Card className="bg-slate-800/30 border-slate-700">
        <CardHeader className="pb-2">
          <CardTitle className="text-xs text-slate-400">Documents</CardTitle>
        </CardHeader>
        <CardContent className="space-y-2 text-xs">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <FileText className="h-3.5 w-3.5 text-slate-400" />
              <span className="text-slate-300">Bill of Lading</span>
            </div>
            {audit.documents.bol.available ? (
              <span className="text-emerald-400 flex items-center gap-1">
                <CheckCircle className="h-3 w-3" />
                Linked
              </span>
            ) : (
              <span className="text-slate-500">Not available</span>
            )}
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <FileText className="h-3.5 w-3.5 text-slate-400" />
              <span className="text-slate-300">Customs Documents</span>
            </div>
            {audit.documents.customs.available ? (
              <span className="text-emerald-400 flex items-center gap-1">
                <CheckCircle className="h-3 w-3" />
                Linked
              </span>
            ) : (
              <span className="text-slate-500">Not available</span>
            )}
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <FileText className="h-3.5 w-3.5 text-slate-400" />
              <span className="text-slate-300">Proof of Delivery</span>
            </div>
            {audit.documents.pod.available ? (
              <span className="text-emerald-400 flex items-center gap-1">
                <CheckCircle className="h-3 w-3" />
                Linked
              </span>
            ) : (
              <span className="text-slate-500">Not available</span>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Events Snippet */}
      <Card className="bg-slate-800/30 border-slate-700">
        <CardHeader className="pb-2">
          <CardTitle className="text-xs text-slate-400">Events Timeline</CardTitle>
        </CardHeader>
        <CardContent className="space-y-2 text-xs">
          <div className="flex justify-between text-xs">
            <span className="text-slate-400">Total Events</span>
            <span className="font-medium text-slate-200">{audit.events.count}</span>
          </div>
          {audit.events.firstAt && audit.events.lastAt && (
            <div className="flex justify-between text-xs">
              <span className="text-slate-400">Timespan</span>
              <span className="text-slate-300">
                {new Date(audit.events.firstAt).toLocaleDateString()} →{" "}
                {new Date(audit.events.lastAt).toLocaleDateString()}
              </span>
            </div>
          )}
          {audit.events.items.length > 0 && (
            <div className="mt-3 space-y-1.5">
              <p className="text-slate-500 text-xs font-medium">Recent Events:</p>
              {audit.events.items.slice(0, 3).map((event, idx) => (
                <div
                  key={idx}
                  className="flex items-center justify-between py-1 px-2 bg-slate-900/50 rounded"
                >
                  <div className="flex items-center gap-2">
                    {event.severity === "ERROR" && <AlertTriangle className="h-3 w-3 text-rose-400" />}
                    {event.severity === "WARNING" && <AlertTriangle className="h-3 w-3 text-amber-400" />}
                    <span className="text-slate-300">{event.eventType}</span>
                  </div>
                  <time className="text-slate-500 text-xs">
                    {new Date(event.at).toLocaleTimeString()}
                  </time>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Raw JSON Viewer */}
      <details className="mt-3">
        <summary className="cursor-pointer text-xs text-slate-500 hover:text-slate-400 transition-colors">
          View raw AuditPack JSON
        </summary>
        <pre className="mt-2 max-h-72 overflow-auto rounded-lg bg-slate-900 p-3 text-[11px] text-slate-100 border border-slate-700">
          {JSON.stringify(audit, null, 2)}
        </pre>
      </details>
    </div>
  );
}
