from enum import Enum

class EventType(str, Enum):
    SHIPMENT_UPDATE = "SHIPMENT_UPDATE"
    RISK_OK = "RISK_OK"
    RISK_FAIL = "RISK_FAIL"
    PAYMENT_TRIGGER = "PAYMENT_TRIGGER"
    TOKEN_EVENT = "TOKEN_EVENT"
    SHIPMENT_DELIVERED = "SHIPMENT_DELIVERED"
    IOT_ANOMALY = "IOT_ANOMALY"
    RULE_TRIGGER = "RULE_TRIGGER"
    SETTLEMENT_STARTED = "SETTLEMENT_STARTED"
    SETTLEMENT_MILESTONE_PAID = "SETTLEMENT_MILESTONE_PAID"
    SETTLEMENT_FINALIZED = "SETTLEMENT_FINALIZED"
    SETTLEMENT_HELD_RISK = "SETTLEMENT_HELD_RISK"
    # Add more as needed
